import { Inter } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "./context";
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import 'aos/dist/aos.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "9jaLingua",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextProvider>
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
          {children}
        </AppContextProvider>
      </body>
    </html>
  );
}
